server:
  port: 7979
  max-http-header-size: 102400
  tomcat:
    uri-encoding: utf-8
    max-http-post-size: 102400

spring:
  profiles:
    active: dev
  application:
    name: paascloud-gateway

swagger:
  title: paascloud-gateway
  description: swagger description