server:
  port: 9000
  max-http-header-size: 102400
  tomcat:
    uri-encoding: utf-8
    max-http-post-size: 102400

spring:
  profiles:
    active: dev
  application:
    name: paascloud-service-web
  datasource:
    url: jdbc:mysql://paascloud-db-mysql:3306?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456